name: Build with conda
on:
  push:

jobs:
  unix:
    strategy:
      matrix:
        include:
          - os: macos-latest
            mongo_bin:  /Users/runner/micromamba-root/envs/arcticdb/bin
          - os: ubuntu-latest
          mongo_bin:  /home/runner/micromamba-root/envs/arcticdb/bin
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Conda environment from environment_unix.yml
        uses: mamba-org/provision-with-micromamba@main

        with:
          environment-file: environment_unix.yml
          environment-name: arcticdb

      - name: Build ArcticDB with conda (ARCTICDB_USING_CONDA=1)
        shell: bash -l {0}
        run: |
          python -m pip install -v -e .
        env:
          ARCTICDB_USING_CONDA: 1


      - name: Test with pytest
        shell: bash -l {0}
        run: |
          cd python
          python -m pytest tests
        env: 
          SERVER_FIXTURES_MONGO_BIN: ${{ matrix.mongo_bin }}